cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala

scala:
   - 2.11.8
   - 2.12.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

jdk:
  - oraclejdk8

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
